import type { Metadata } from 'next'
import { Source_Serif_4 } from 'next/font/google'
import './globals.css'
import { Navbar } from '@/components/navbar'

const serif = Source_Serif_4({
  variable: '--font-serif',
  subsets: ['latin'],
  // weight: ['200', '300', '400'],
  weight: ['200', '400', '700'],
  style: ['italic', 'normal'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${serif.variable} antialiased font-serif text-base text-gray-700 bg-white border-8 border-solid border-gray-200`}
      >
        <a className="skip-link" href="#main">
          Skip to content
        </a>
        <div className="flex flex-col min-h-screen flex-none">
          <div className="container mx-auto px-3 flex flex-row flex-wrap justify-between items-center pt-2 mb-6 sm:mb-12 md:mb-24">
            <Navbar />
          </div>

          <main className="flex-auto" id="main">
            {children}
          </main>

          <footer className="flex-none container mx-auto px-3" id="contact">
            <div className="px-3 w-full flex-none mb-3">
              <hr className="w-full h-0 block border-t border-solid border-red-600 py-0 m-0" />
            </div>
            <div className="flex flex-row flex-wrap justify-end">
              <div className="px-3 w-full md:w-1/2 lg:w-1/3 xl:w-1/4 mb-12">
                <div className="generated">© 2025 Dimitris Kottas</div>
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  )
}
